import { useEffect, useMemo, useState } from "react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Copy, Check } from "lucide-react";
import { scrubPII, type IncidentRecord } from "@/data/mockData";

const minutesBetween = (a: string, b: string) =>
  Math.max(1, Math.round((new Date(b).getTime() - new Date(a).getTime()) / 60000));

const buildMarkdown = (r: IncidentRecord) => {
  const ttr = minutesBetween(r.zendesk.created_at, r.jira.resolved_at);
  return `# Post-Mortem · ${r.scenario}

**Incident:** ${r.zendesk.ticket_id} ↔ ${r.jira.issue_id}
**Component:** ${r.jira.component}
**Severity:** ${r.zendesk.priority}
**Time to Resolution:** ${ttr} minutes

---

## 1. Summary
A customer-reported issue ("${r.zendesk.subject}") was traced to a backend defect in the **${r.jira.component}** component. The root cause was identified and remediated by the engineering team.

## 2. Customer Impact (Symptom)
${scrubPII(r.zendesk.description)}

> Reported via ${r.zendesk.ticket_id} at ${new Date(r.zendesk.created_at).toUTCString()}.

## 3. Root Cause Analysis
${r.jira.description}

## 4. Resolution
${r.jira.resolution}

## 5. Timeline
- **${new Date(r.zendesk.created_at).toUTCString()}** — Ticket ${r.zendesk.ticket_id} opened by customer.
- **Engineering hand-off** — Linked to ${r.jira.issue_id} after agent triage.
- **${new Date(r.jira.resolved_at).toUTCString()}** — Fix deployed; ${r.jira.issue_id} resolved.

## 6. Action Items
- [ ] Add regression test covering the **${r.jira.component}** failure path.
- [ ] Update internal runbook for "${r.scenario}".
- [ ] Notify support team so similar tickets can be auto-tagged.

---
*Generated by RCA Engine · PII scrubbed before processing.*
`;
};

export const RcaReport = ({ record }: { record: IncidentRecord }) => {
  const md = useMemo(() => buildMarkdown(record), [record]);
  const [typed, setTyped] = useState("");
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    setTyped("");
    let i = 0;
    const id = setInterval(() => {
      i += 18;
      setTyped(md.slice(0, i));
      if (i >= md.length) clearInterval(id);
    }, 12);
    return () => clearInterval(id);
  }, [md]);

  const copy = async () => {
    await navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  return (
    <Card className="border-border/80 shadow-sm overflow-hidden">
      <div className="flex items-center justify-between px-5 py-3 border-b bg-muted/40">
        <div>
          <div className="text-xs uppercase tracking-wider text-muted-foreground">
            AI-Generated Post-Mortem
          </div>
          <div className="text-sm font-semibold">
            {record.zendesk.ticket_id} · {record.scenario}
          </div>
        </div>
        <Button size="sm" variant="outline" onClick={copy}>
          {copied ? (
            <>
              <Check className="h-4 w-4" /> Copied
            </>
          ) : (
            <>
              <Copy className="h-4 w-4" /> Copy Markdown
            </>
          )}
        </Button>
      </div>
      <div className="p-6">
        <article className="prose-rca">
          <FormattedMarkdown text={typed} />
        </article>
      </div>
    </Card>
  );
};

const FormattedMarkdown = ({ text }: { text: string }) => {
  const lines = text.split("\n");
  const out: JSX.Element[] = [];
  let list: string[] | null = null;
  const flushList = () => {
    if (list) {
      out.push(
        <ul key={`ul-${out.length}`} className="list-disc pl-5 space-y-1 my-2">
          {list.map((li, i) => (
            <li key={i} className="text-sm text-foreground/90">
              {renderInline(li)}
            </li>
          ))}
        </ul>
      );
      list = null;
    }
  };

  lines.forEach((raw, idx) => {
    const line = raw;
    if (line.startsWith("# ")) {
      flushList();
      out.push(
        <h1 key={idx} className="text-2xl font-bold tracking-tight mb-2">
          {line.slice(2)}
        </h1>
      );
    } else if (line.startsWith("## ")) {
      flushList();
      out.push(
        <h2
          key={idx}
          className="text-base font-semibold uppercase tracking-wider text-primary mt-5 mb-2"
        >
          {line.slice(3)}
        </h2>
      );
    } else if (line.startsWith("> ")) {
      flushList();
      out.push(
        <blockquote
          key={idx}
          className="border-l-2 border-accent pl-3 my-2 text-sm text-muted-foreground italic"
        >
          {renderInline(line.slice(2))}
        </blockquote>
      );
    } else if (line.startsWith("- ")) {
      if (!list) list = [];
      list.push(line.slice(2));
    } else if (line.trim() === "---") {
      flushList();
      out.push(<hr key={idx} className="my-4 border-border" />);
    } else if (line.trim() === "") {
      flushList();
    } else {
      flushList();
      out.push(
        <p key={idx} className="text-sm leading-relaxed text-foreground/90 my-1.5">
          {renderInline(line)}
        </p>
      );
    }
  });
  flushList();
  return <>{out}</>;
};

const renderInline = (s: string) => {
  const parts = s.split(/(\*\*[^*]+\*\*|`[^`]+`)/g);
  return parts.map((p, i) => {
    if (p.startsWith("**") && p.endsWith("**"))
      return (
        <strong key={i} className="font-semibold text-foreground">
          {p.slice(2, -2)}
        </strong>
      );
    if (p.startsWith("`") && p.endsWith("`"))
      return (
        <code
          key={i}
          className="font-mono-terminal text-xs bg-muted px-1.5 py-0.5 rounded border border-border"
        >
          {p.slice(1, -1)}
        </code>
      );
    return <span key={i}>{p}</span>;
  });
};
